// Bundled workflow instructions are installed by `autodev init`.
pub const FILES: &[(&str, &str)] = &[
    (
        "stages/quality.md",
        include_str!("../workflow/stages/quality.md"),
    ),
    (
        "stages/implementation.md",
        include_str!("../workflow/stages/implementation.md"),
    ),
    (
        "stages/discovery.md",
        include_str!("../workflow/stages/discovery.md"),
    ),
    ("NOTICE.md", include_str!("../workflow/NOTICE.md")),
    ("PARITY.md", include_str!("../workflow/PARITY.md")),
    (
        "stages/planning.md",
        include_str!("../workflow/stages/planning.md"),
    ),
    (
        "commands/analyze.md",
        include_str!("../workflow/commands/analyze.md"),
    ),
    (
        "commands/checklist.md",
        include_str!("../workflow/commands/checklist.md"),
    ),
    (
        "commands/clarify.md",
        include_str!("../workflow/commands/clarify.md"),
    ),
    (
        "commands/constitution.md",
        include_str!("../workflow/commands/constitution.md"),
    ),
    (
        "commands/implement.md",
        include_str!("../workflow/commands/implement.md"),
    ),
    (
        "commands/plan.md",
        include_str!("../workflow/commands/plan.md"),
    ),
    (
        "commands/specify.md",
        include_str!("../workflow/commands/specify.md"),
    ),
    (
        "commands/tasks.md",
        include_str!("../workflow/commands/tasks.md"),
    ),
    (
        "commands/taskstoissues.md",
        include_str!("../workflow/commands/taskstoissues.md"),
    ),
    (
        "templates/agent-file-template.md",
        include_str!("../workflow/templates/agent-file-template.md"),
    ),
    (
        "templates/checklist-template.md",
        include_str!("../workflow/templates/checklist-template.md"),
    ),
    (
        "templates/constitution-template.md",
        include_str!("../workflow/templates/constitution-template.md"),
    ),
    (
        "templates/plan-template.md",
        include_str!("../workflow/templates/plan-template.md"),
    ),
    (
        "templates/spec-template.md",
        include_str!("../workflow/templates/spec-template.md"),
    ),
    (
        "templates/tasks-template.md",
        include_str!("../workflow/templates/tasks-template.md"),
    ),
];
