// Bundled workflow instructions are installed by `autodev init`.
pub const FILES: &[(&str, &str)] = &[
    ("NOTICE.md", include_str!("../workflow/NOTICE.md")),
    ("PARITY.md", include_str!("../workflow/PARITY.md")),
    (
        "stages/planning.md",
        include_str!("../workflow/stages/planning.md"),
    ),
    (
        "commands/analyze.md",
        include_str!("../workflow/commands/analyze.md"),
    ),
    (
        "commands/checklist.md",
        include_str!("../workflow/commands/checklist.md"),
    ),
    (
        "commands/clarify.md",
        include_str!("../workflow/commands/clarify.md"),
    ),
    (
        "commands/constitution.md",
        include_str!("../workflow/commands/constitution.md"),
    ),
    (
        "commands/implement.md",
        include_str!("../workflow/commands/implement.md"),
    ),
    (
        "commands/plan.md",
        include_str!("../workflow/commands/plan.md"),
    ),
    (
        "commands/specify.md",
        include_str!("../workflow/commands/specify.md"),
    ),
    (
        "commands/tasks.md",
        include_str!("../workflow/commands/tasks.md"),
    ),
    (
        "commands/taskstoissues.md",
        include_str!("../workflow/commands/taskstoissues.md"),
    ),
    (
        "roles/async-task-implementer.md",
        include_str!("../workflow/roles/async-task-implementer.md"),
    ),
    (
        "roles/backend-architect.md",
        include_str!("../workflow/roles/backend-architect.md"),
    ),
    (
        "roles/database-architect.md",
        include_str!("../workflow/roles/database-architect.md"),
    ),
    (
        "roles/devops-infrastructure.md",
        include_str!("../workflow/roles/devops-infrastructure.md"),
    ),
    (
        "roles/docs-maintainer.md",
        include_str!("../workflow/roles/docs-maintainer.md"),
    ),
    (
        "roles/frontend-developer.md",
        include_str!("../workflow/roles/frontend-developer.md"),
    ),
    (
        "roles/master-orchestrator.md",
        include_str!("../workflow/roles/master-orchestrator.md"),
    ),
    (
        "roles/realtime-integration-specialist.md",
        include_str!("../workflow/roles/realtime-integration-specialist.md"),
    ),
    (
        "roles/scrum-master-pm.md",
        include_str!("../workflow/roles/scrum-master-pm.md"),
    ),
    (
        "roles/test-guardian.md",
        include_str!("../workflow/roles/test-guardian.md"),
    ),
    (
        "templates/agent-file-template.md",
        include_str!("../workflow/templates/agent-file-template.md"),
    ),
    (
        "templates/checklist-template.md",
        include_str!("../workflow/templates/checklist-template.md"),
    ),
    (
        "templates/constitution-template.md",
        include_str!("../workflow/templates/constitution-template.md"),
    ),
    (
        "templates/plan-template.md",
        include_str!("../workflow/templates/plan-template.md"),
    ),
    (
        "templates/spec-template.md",
        include_str!("../workflow/templates/spec-template.md"),
    ),
    (
        "templates/tasks-template.md",
        include_str!("../workflow/templates/tasks-template.md"),
    ),
];
